# Generated by Django 5.0.6 on 2024-06-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_likes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
